repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [
            '-e', 'git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes',
            '-e', 'git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle',
        ]
        exclude: backend/settings/settings.py
        args: [ --config=src/.flake8 ]