from .user_views import RegisterView, MeDetailView
from .action_views import ActionListView, CreateNewActionView, RetrieveUpdateDestroyActionView
from .ingredient_views import IngredientListView, CreateNewIngredientView, RetrieveUpdateDestroyIngredientView
from .device_views import DeviceListView, CreateNewDeviceView, RetrieveUpdateDestroyDeviceView
from .recipy_views import RecipyListView, CreateNewRecipyView, RetrieveUpdateDestroyRecipyView
